added .env for docker build

diff --git a/web-frontend/dockerfile b/web-frontend/dockerfile
--- a/web-frontend/dockerfile
+++ b/web-frontend/dockerfile
@@ -1,22 +1,31 @@
 # syntax=docker.io/docker/dockerfile:1
 
+
 FROM node:20-alpine AS base
 
 # Install dependencies only when needed
 FROM base AS deps
 # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 RUN apk add --no-cache libc6-compat
+
 WORKDIR /app
+
+# Check for .env for production build
+COPY .env ./
+RUN if [ -f .env ]; then \
+      echo "Using .env in production build"; \
+    else \
+      echo "No .env found, generate it with create_dotenv.sh" && exit 1; \
+    fi
 
 # Install dependencies based on the preferred package manager
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
 RUN \
-  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  elif [ -f package-lock.json ]; then npm ci; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
-
+if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+elif [ -f package-lock.json ]; then npm ci; \
+elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+else echo "Lockfile not found." && exit 1; \
+fi
 
 # Rebuild the source code only when needed
 FROM base AS builder
